### PR TITLE
Do not use parameters for private classes

### PR DESCRIPTION
**Pull request by smortex**
Private classes with parameters make it possible for end-users to pass
custom values to these private classes via Hiera and break things.

If we do not have such parameters, we make breakage less likely.

### CODE REVIEW

**Comment by crazymind1337** [comment]
You might need to adjust the rspec test to according to your changes.

**Comment by smortex** [comment]
Hum, I don't think these parameters where tested, and the CI is passing.  Do you have a point of attention in mind?

**Comment by crazymind1337** [comment]
Nevermind - I have done it for you :D I think I didn't not express my needs correctly.

**Review by crazymind1337 — APPROVED** [review]
Looks good now.

**Pull request merged**
